version: 2
registries:
  luxious-repo:
    type: maven-repository
    url: https://repo.luxiouslabs.net/repository/luxious-private
    username: ${{ secrets.LUXIOUS_NEXUS_USER }}
    password: ${{ secrets.LUXIOUS_NEXUS_PASS }}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries: '*'
    schedule:
      interval: "daily"
    groups:
      default:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
