rootProject.name = "FactionIntegrations"
include("factions-atlas")
include("common")
include("factions-jartex")
include("factions-jerry")
include("factions-joseph")
include("factions-mc1.20")
include("factions-newuuid")
include("factions-saber")
include("factions-saberx")
include("factions-stellar")
include("factions-uuid")
