name: Maven Build (Pull Request)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    #--------------------------------------------------------------------------------------------
    #           Build the Artifact
    #--------------------------------------------------------------------------------------------
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Maven Settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "luxious-factions-libs", "username": "${{ secrets.LUXIOUS_LIBS_NAME }}", "password": "${{ secrets.LUXIOUS_LIBS_SECRET }}"}]'

      - name: Build
        run: mvn -B package --file pom.xml